cartong/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('cnls.urls')),
    url(r'', include('feedback.urls')),
]

cnls/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from cnls import views

urlpatterns = patterns('',
    # La carte (écran d'accueil)
    url(r'^$', views.home, name='home'),
    # Une page affichant le GeoJson format texte (utilisé seulement à des fins de test)
    url(r'^geoactions\/?$', views.get_geoactions, name='geoactions'),
    # Le fichier robots.txt à destination des "web crawlers"
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
#    url(r'(?i)^(?P<action_echelle>[a-zA-Z]+)\/(?P<action_id>[0-9]+)/$', views.detail, name='detail'),
    # L'onglet À propos
    url(r'^a_propos\/?$', views.apropos, name='apropos'),
    # Le chargement du fichier CSV d'export
    url(r'^actions$', views.export_csv, name='export_csv'),
    # La vue détaillée de l'action choisir
    url(r'^(?P<classe>[a-zA-Z]+)\/(?P<id>\d+)\/.*$', views.detail, name='detail'),
    #favicons
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/media/favicons/favicon.ico', permanent=True)),
    url(r'^android-chrome-192x192\.png$', RedirectView.as_view(url='/static/media/favicons/android-chrome-192x192.png', permanent=True)),
    url(r'^browserconfig\.xml$', RedirectView.as_view(url='/static/media/favicons/browserconfig.xml', permanent=True)),
    url(r'^mstile-150x150\.png$', RedirectView.as_view(url='/static/media/favicons/mstile-150x150.png', permanent=True)),
    # Inusité
    #url(r'^faritra/$', views.get_faritra, name='faritra'),
)

feedback/models.py
from django.db import models

TYPES = (('bug', 'Signaler un bug'), ('amélioration', 'Suggérer une amélioration'), ('question', 'Poser une question'), ('commentaire', 'Faire un commentaire'))
GRAVITE = (('1', "1 (C'est un détail)"), ('2','2'), ('3','3 (Important)'), ('4','4'), ('5','5 (Essentiel)'))

class Feedback(models.Model):
    type = models.CharField(max_length=50, choices=TYPES, verbose_name="Type d'information à nous transmettre")
    echelle = models.CharField(max_length=10, choices=GRAVITE, verbose_name="Quel est le niveau de gravité de votre problème / question ?")
    description = models.TextField(blank=False, null=False, default="", verbose_name="Quel a été le problème rencontré ? Merci de décrire précisément l'action que vous étiez en train d'effectuer")
    suggestion = models.TextField(blank=True, null=True, default="", verbose_name="Que souhaitez-vous voir modifier ?")
    nom = nom = models.CharField(max_length=100, verbose_name="Votre nom")
    email = models.EmailField(verbose_name="Votre adresse mail")
    date = models.DateField(auto_now_add=True, null=True)

    class Meta:
        managed = True
        verbose_name = "Bug, suggestion, question ou commentaire"
        verbose_name_plural = "Bugs, suggestions, questions et commentaires"

cnls/forms.py
from django import forms
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.contrib.gis.geos import Point, MultiPoint
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
import re
from cnls.models import Action, Organisme, Profil

####################
# Modification du formulaire par défaut pour la création et la modification d'utilisateurs
####################
class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        # Ces champs seront obligatoires (ce n'est pas le cas par défaut pour le modèle User)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    # Champs supplémentaires du modèle Profil
    organisme = forms.ModelChoiceField(queryset=Organisme.objects.all(), to_field_name="nom")
    poste = forms.CharField(max_length=250, required=False)
    photo = forms.ImageField(required=False)

    class Meta:
        model = User
        exclude = []

    # Personnalisation du choix du groupe
    groups = forms.ModelChoiceField(queryset=Group.objects.all().order_by('-name'), widget=forms.RadioSelect, empty_label=None, initial=1)
    # Et comme Django attend une liste de groupes
    def clean(self):
        # D'abord la méthode par défaut
        cleaned_data = super(CustomUserCreationForm, self).clean()
        # puis on récupère le groupe pour en faire une liste
        groupe = cleaned_data.get('groups')
        cleaned_data['groups'] = [groupe,]
        return cleaned_data

    # On enregistre le modèle User avec la procédure par défaut, et à part les champs du modèle Profil
    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=True)
        user_profile = Profil(user=user, organisme=self.cleaned_data['organisme'], poste=self.cleaned_data['poste'], photo=self.cleaned_data['photo'])
        user_profile.save()
        return user

class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        # du bricolage pour que le RadioButton soit content de ne recevoir qu'un groupe à la fois
        # (s'il y en a plusieurs rien ne s'affichera dans le RadioButton et l'utilisateur devra en choisir un)
        user = kwargs['instance']
        if (user.groups.all().count() == 1):
            (group,) = user.groups.all()
            kwargs['initial'] = {'groups': group}
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    # Personnalisation du choix du groupe
    groups = forms.ModelChoiceField(queryset=Group.objects.all().order_by('-name'), widget=forms.RadioSelect, empty_label=None)
    # Et comme Django attend une liste de groupes
    def clean(self):
        # D'abord la méthode par défaut
        cleaned_data = super(CustomUserChangeForm, self).clean()
        # puis on récupère le groupe pour en faire une liste
        groupe = cleaned_data.get('groups')
        cleaned_data['groups'] = [groupe,]
        return cleaned_data


####################
####################
# Expression régulière pour récupérer latitudes et longitudes entrées par l'utilisateur
#reg = re.compile(r'^\s*\(\s*(-?\s*\d+(?:\.\d+)?)\s*,\s*(-?\s*\d+(?:\.\d+)?)\s*\)\s*$')
regex = r'^\s*(-?\s*\d+(?:\.\d+)?)\s*,\s*(-?\s*\d+(?:\.\d+)?)\s*$'

class CustomAdminForm(forms.ModelForm):
    def validate_multipoint(value):
        for line in value.splitlines():
            # Les coordonnées sont attendues une par ligne, sous la forme : latitude, longitude
            # comme spécifié dans le help_text du champ mpoint_text
            match = re.match(regex, line)
            if not match:
                raise ValidationError('(%(line)s) n\'est pas au format attendu.', params={'line': line}, code='invalid')
            lat = float(match.group(1).replace(" ",""))
            lon = float(match.group(2).replace(" ",""))
            # Test très grossier pour vérifier qu'il n'y a pas eu d'inversion entre latitude et longitude
            if not (-26<lat<-11 and 42<lon<52):
                raise ValidationError('Le point %(line)s n\'est pas situé à Madagascar.', params={'line': line}, code='invalid')

    mpoint_text = forms.CharField(label = 'Coordonnées GPS', help_text = "Veuillez renseigner les coordonnées ligne par ligne, sous la forme : latitude, longitude", required = False, widget = forms.Textarea, validators=[validate_multipoint])  
    # TODO choix srid?

    def clean(self):
        # D'abord la méthode par défaut
        cleaned_data = super(CustomAdminForm, self).clean()
        # puis on récupère le contenu de certains champs pour faire des validations particulières
        mpoint_text = cleaned_data.get("mpoint_text")
        mpoint = cleaned_data.get("mpoint")
        # S'assurer qu'au moins une localisation a été fournie
        if (not mpoint) and (not mpoint_text):
            self.add_error('mpoint', ValidationError("Veuillez renseigner au moins une localisation (carte ou coordonnées GPS).", code='invalid'))
        # S'assurer qu'il n'y ait pas des données et sur la carte et dans le champ texte pour éviter les doublons
        if mpoint and mpoint_text:
            self.add_error('mpoint', ValidationError("Pour éviter les doublons, merci de renseigner uniquement la carte OU les coordonnées.", code='invalid'))
        if mpoint_text:
            points = []
            # On récupère les coordonnées remplies à la main pour en faire un une géométrie
            for line in mpoint_text.splitlines():
                match = re.match(regex, line)
                lat = float(match.group(1).replace(" ",""))
                lon = float(match.group(2).replace(" ",""))
                points.append(Point(lon, lat, srid=4326))
            # on envoie le MultiPoint créé sur le champ mpoint
            cleaned_data['mpoint'] = MultiPoint(points)

        # S'assurer qu'une devise a été choisie si un montant a été rentré
        montant_prevu = cleaned_data.get("montant_prevu")
        montant_disponible = cleaned_data.get("montant_disponible")
        devise = cleaned_data.get("devise")
        if (montant_prevu or montant_disponible) and not devise:
            self.add_error('devise', ValidationError("Veuillez préciser la devise des fonds.", code='invalid'))
        # On retourne le contenu des champs pour enregistrement par Django
        return cleaned_data

    class Meta:
        model = Action
        exclude = []

cnls/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse
from django.template import Context, loader
from django.core import serializers
from cnls.geojson_serializer_with_id import GeojsonWithIdSerializer
from django.shortcuts import get_object_or_404 #, render, redirect
from django.db.models import get_model
from django.db.models import Q
#from django.forms.models import model_to_dict
from datetime import datetime
import csv

from cnls.forms import CustomAdminForm
from cnls.models import DICT_ECHELLES, ActionNationale, ActionTananarive, ActionRegionale, ActionLocale, TypeIntervention, Cible

####################
# La page d'accueil du site (index.html)
def home(request):
#    return redirect('http://cartong.github.io/mada-front/dist/atlas/index.html', permanent=True)
    template = loader.get_template('cnls/index.html')
    def to_json(echelle):
        # Convertit en GeoJson les actions validées par un administrateur, grâce au "serializer" personnalisé de geojson_serializer_with_id.py
        return GeojsonWithIdSerializer().serialize(echelle.objects.filter(validation='valide'), srid='4326', use_natural_foreign_keys=True)
        # NB GeojsonWithIdSerializer a été configuré pour ne renvoyer que les champs qui sont utilisés dans le popup - comportement à modifier si besoin dans geojson_serializer_with_id.py

    # Données envoyées à index.html, comprenant les différents niveaux d'échelle, les cibles et types d'intervention (pour les filtres)
    return HttpResponse(template.render(Context({
        'actionsN' : to_json(ActionNationale),
        'actionsT' : to_json(ActionTananarive),
        'actionsR' : to_json(ActionRegionale),
        'actionsL' : to_json(ActionLocale),
        'typesinterventions' : TypeIntervention.objects.all(),
        'cibles' : Cible.objects.all(),
        })))

####################
# Page de détail d'une action dont la primary key est id
def detail(request, classe, id):
    template = loader.get_template('cnls/detail.html')
    model = get_model('cnls', classe)
    # Si l'id n'est pas trouvé dans la classe, renvoie une erreur 404 (not found)
    return HttpResponse(template.render(Context({'action' : get_object_or_404(model.objects.prefetch_related(), pk=id)})))

####################
# Page renvoyant au format texte le GeoJson correpondant à la base de données
# NB à des fins de test seulement, TODO à supprimer à terme ou u moins à filtrer sur les actions validées
def get_geoactions(request):
    def to_json(echelle):
        return GeojsonWithIdSerializer().serialize(echelle.objects.all(), srid='4326', use_natural_foreign_keys=True)
        #return serializers.serialize('geojson', echelle.objects.all(), srid='4326', use_natural_foreign_keys=True)

    data = {
        to_json(ActionNationale),
        to_json(ActionTananarive),
        to_json(ActionRegionale),
        to_json(ActionLocale),
        }
#    data = serializers.serialize('geojson', ActionTananarive.objects.all(), srid='4326', use_natural_foreign_keys=True)
    return HttpResponse(data, content_type='application/json')

####################
# Pour quand on aura la géographie des nouvelles régions
#def get_faritra(request):
#    faritra = open(djangoSettings.STATIC_ROOT + 'json/faritra.json', 'r')
#    #faritra = serializers.serialize('json', data)
#    return HttpResponse(faritra)

####################
# Crée le fichier CSV d'export
def export_csv(request, ids=None):  
    # On récupère l'id transmise par l'url (parmi les paramètres après le ?
    params = request.GET.getlist('id', default=None)
    response = HttpResponse(content_type='text/csv')
    # Le fichier téléchargé par l'utilisateur d'appelera CNLS_selection.csv
    response['Content-Disposition'] = 'attachment; filename="CNLS_selection.csv"'

    writer = csv.writer(response, quoting=csv.QUOTE_NONNUMERIC)
    # On crée les colonnes correspondants aux champs qui seront exportés
    writer.writerow(["Titre", "Description", "Organisme maître d'œuvre", "Types d'interventions", "Publics cibles", "Echelle", "Localisation", "Coordonnées géographiques", "Date de démarrage", "Date de fin", "Durée de l'action", "Etat d'avancement", "Nombre de personnes visées", "Opérateur en lien avec l'action", "Priorité du PSN que l'activité appuie", "Résultat par rapport à l'année précédente", "Montant prévu", "Montant disponible", "Devise", "Bailleur de fond", "Origine de la donnée", "Commentaires", "Nom du responsable de la fiche", "Fiche créée le", "Dernière modification le"])
    # On récupère les échelles transmise par l'url (paramètre e après le ? )
    echelles = request.GET.getlist('e', '')
    if echelles:
        #try:
        # On récupère les cibles (paramètre c) passées par l'url
        cibles = Cible.objects.all().filter(nom__in = request.GET.getlist('c', ''))
        #except Cible.empty:
        #pass
        # On récupère les types d'intervention (paramètre t) passés par l'url
        types = TypeIntervention.objects.all().filter(nom__in = request.GET.getlist('t', ''))
        for echelle in echelles:
            model = get_model('cnls', echelle)
            champ_localisation = DICT_ECHELLES[model.__name__]['champ']
            # On récupère les objets de la base de données validant les différents filtres
            queryset = model.objects.all().filter(validation='valide').filter(typeintervention__in = types).filter(Q(date_debut__lte = datetime.strptime(request.GET.get('f'), '%Y-%m-%d').date()) | Q(date_debut__isnull=True)).filter(Q(date_fin__gte = datetime.strptime(request.GET.get('d'), '%Y-%m-%d').date()) | Q(date_fin__isnull=True))

            # On écrit une ligne par objet dans le CSV
            for action in queryset:
                test = getattr(action, champ_localisation).all()
                # Pour l'objet considéré, on écrit les valeurs des différentes colonnes dans le même ordre que les colonnes définies ci-dessous
                writer.writerow([
                    action.titre,
                    action.description,
                    action.organisme,
                    ', '.join([str(t) for t in action.typeintervention.all()]),
                    ', '.join([str(c) for c in action.cible.all()]),
                    DICT_ECHELLES[model.__name__]['adj_fr'],
                    ', '.join([str(l) for l in getattr(action, champ_localisation).all()]),
                    action.mpoint,
                    action.date_debut,
                    action.date_fin,
                    action.duree,
                    action.avancement,
                    action.objectif,
                    action.operateur,
                    action.priorite_psn,
                    action.resultat_cf_annee_ant,
                    action.montant_prevu,
                    action.montant_disponible,
                    action.devise,
                    action.bailleur,
                    action.origine,
                    action.commentaire,
                    action.createur,
                    action.creation,
                    action.maj
                ])

    # normalement ce cas n'est pas rencontré car filtré par le JavaScript mais au cas où une URL serait écrite à la main:
    else:
        return
    return response

####################
# La page À propos
def apropos(request):
    template = loader.get_template('cnls/apropos.html')
    return HttpResponse(template.render())

cnls/templates/cnls/index.html
{% extends 'cnls/base.html' %}

{% load staticfiles %}

{% block custom_head %} 
  <link rel="stylesheet" href="https://unpkg.com/leaflet@0.7.7/dist/leaflet.css" /> <!-- à passer à 1.0.0 pour coller avec le js-->
  <link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/Leaflet/Leaflet.markercluster/v1.0.0-beta.2.0/dist/MarkerCluster.Default.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/Leaflet/Leaflet.markercluster/v1.0.0-beta.2.0/dist/MarkerCluster.css">

  <script type="text/javascript">
var actionsNationales = {{actionsN|safe}};
var actionsTananarive = {{actionsT|safe}};
var actionsRegionales = {{actionsR|safe}};
var actionsLocales = {{actionsL|safe}};
  </script>
{% endblock custom_head %}

{% block open_body %}<body onload="init();">{% endblock %}  

{% block onglet_carte %}class="active"{% endblock %}

{% block drapeau %}<img alt="Français" src="{% static "./assets/img/locale_fr-FR.png" %}">{% endblock %}

{% block content %}
  <div class="container-fluid fill">

      <div class="collapse in" id="accordion">

        <!--bug link panel-->
        <div class="panel  panel--inner">
          <div class="panel-heading" role="tab">
            <h4 class="panel-title">
              <a class="collapsed panel-title-inner" id="bug" href="{% url 'bugs' %}">&#8594; Signaler un bug</a>
            </h4>
          </div>
          <div class="panel-collapse collapse" role="tabpanel">
          </div>
        </div><!--/bug link panel 

        <!--count panel -->
        <div class="panel panel--inner">
          <div class="panel-heading count" role="tab">
            <h4 class="panel-title count"><span id="markersCount">...</span> actions affichées</h4>
          </div>
        </div><!--/count panel -->


        <!--echelles panel -->
        <div class="panel panel--inner">
          <div class="panel-heading" role="tab" id="actionTypeHeading">
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#echelle" aria-expanded="true" aria-controls="echelle" class="panel-title-inner" data-parent="#accordion">
                &Eacute;chelles d&#39;intervention
              </a>
            </h4>
          </div>

          <div id="echelle" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="actionTypeHeading">
          
            <div class="panel-body checkboxAll">       
              <label>
                <input type="checkbox" checked onClick="toggleAll(this, 'echelle')"><i>Tout dé-/sélectionner</i>
              </label>
            </div>
            <div class="panel-body checkboxList js-filter-checkboxes" data-filter-checkboxes-field="echelle">
              
              <label><input type="checkbox" checked data-filter-checkbox-value="ActionNationale">Actions nationales</label>
              <label><input type="checkbox" checked data-filter-checkbox-value="ActionTananarive">Actions &agrave; Tananarive</label>
              <label><input type="checkbox" checked data-filter-checkbox-value="ActionRegionale">Actions r&eacute;gionales</label>
              <label><input type="checkbox" checked data-filter-checkbox-value="ActionLocale">Actions locales</label>
            </div>
          </div>
        </div><!--/echelles panel -->


        <!--actionType panel -->
        <div class="panel panel--inner">
          <div class="panel-heading" role="tab" id="actionTypeHeading">
            <h4 class="panel-title">
              <a class="collapsed panel-title-inner" data-toggle="collapse" data-parent="#accordion" href="#actionType" aria-expanded="false" aria-controls="actionType"  class="panel-title-inner">
                Types d'actions
              </a>
            </h4>
          </div>

          <div id="actionType" class="panel-collapse collapse" role="tabpanel" aria-labelledby="actionTypeHeading">
            <div class="panel-body checkboxAll">       
              <label>
                <span class="icon" style="background-image: url({% static "./media/picto/blank.png" %})"></span>
                <input type="checkbox" checked onClick="toggleAll(this, 'typeintervention')"><i>Tout dé-/sélectionner</i>
              </label>
            </div>
            <div class="panel-body checkboxList js-filter-checkboxes" data-filter-checkboxes-field="typeintervention">
              {% for type in typesinterventions %}
              {% with "./media/picto/typeintervention-"|add:type.nom|add:".png" as pictoType %}         
              <label>
                <span class="icon" style="background-image: url({% static pictoType %})"></span>
                <input type="checkbox" checked data-filter-checkbox-value="{{type.nom}}">
                <abbr title="{{type.descriptif}}">{{type.get_nom_display}}</abbr>
              </label>
              {% endwith %}
              {% endfor %}
            </div>
          </div>
        </div><!--/actionType panel -->


        <!--populations panel -->
        <div class="panel  panel--inner">
          <div class="panel-heading" role="tab" id="populationHeading">
            <h4 class="panel-title">
              <a class="collapsed panel-title-inner" data-toggle="collapse" data-parent="#accordion" href="#population" aria-expanded="false" aria-controls="population" >
                Populations
              </a>
            </h4>
          </div>
          <div id="population" class="panel-collapse collapse" role="tabpanel" aria-labelledby="populationHeading">
            <div class="panel-body checkboxAll">       
              <label>
                <span class="icon" style="background-image: url({% static "./media/picto/blank.png" %})"></span>
                <input type="checkbox" checked onClick="toggleAll(this, 'cible')"><i>Tout dé-/sélectionner</i>
              </label>
            </div>
            <div class="panel-body checkboxList js-filter-checkboxes" data-filter-checkboxes-field="cible">
              {% for cible in cibles %}
              {% with "./media/picto/cible-"|add:cible.nom|add:".png" as pictoCible %}
              <label>
                <span class="icon" style="background-image: url({% static pictoCible %})"></span>
                <input type="checkbox" checked data-filter-checkbox-value="{{cible.nom}}">{{cible.get_nom_display}}
              </label> 
            {% endwith %}   
            {% endfor %}
            </div>
          </div>
        </div><!--/population panel -->


        <!-- date panel -->
        <div class="panel panel--inner">
          <div class="panel-heading" role="tab" id="dateHeading">
            <h4 class="panel-title">
              <a class="collapsed panel-title-inner" data-toggle="collapse" data-parent="#accordion" href="#date" aria-expanded="false" aria-controls="date">
                Dates
              </a>
            </h4>
          </div>
          <div id="date" class="panel-collapse collapse" role="tabpanel" aria-labelledby="dateHeading">
            <div class="panel-body js-filter-dates filter-dates" data-filter-dates-field-start="date_debut" data-filter-dates-field-end="date_fin" data-filter-dates-format="YYYY-MM-DD">
              <table><tr>
                <td>De : </td>
                <td><div class="dropdown js-filter-dates-start-month">
                  <button class="btn btn-xs dropdown-toggle" type="button" id="date_start_month" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="js-lbl">-</span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="date_start_month">
                  </ul>
                </div></td>
                <td><div class="dropdown js-filter-dates-start-year">
                  <button class="btn btn-xs dropdown-toggle" type="button" id="date_start_year" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="js-lbl">-</span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="date_start_year">
                  </ul>
                </div></td></tr>
              
                <tr><td>&nbsp;&nbsp;à :</td>
                <td><div class="dropdown js-filter-dates-end-month">
                  <button class="btn btn-xs dropdown-toggle" type="button" id="date_end_month" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="js-lbl">-</span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="date_end_month">
                  </ul>
                </div></td>
                <td><div class="dropdown js-filter-dates-end-year">
                  <button class="btn btn-xs dropdown-toggle" type="button" id="date_end_month" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="js-lbl">-</span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="date_end_month">
                  </ul>
                </div></td></tr>
              </table>
            </div>
          </div>
        </div><!--/date panel -->


        <!--export panel -->
        <div class="panel  panel--inner">
          <div class="panel-heading" role="tab">
            <h4 class="panel-title">
              <a class="collapsed panel-title-inner" id="export" href="javascript:exportCSV();">Exporter la sélection (format .csv)</a>
            </h4>
          </div>
          <div id="export" class="panel-collapse collapse" role="tabpanel" aria-labelledby="exportHeading">    
          </div>
        </div><!--/export panel -->

      </div>  <!--/.panel-group -->


      <div id="map"></div>


      <div class="modal fade" id="attributionModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-body">
              <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
              <div id="attribution"></div>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

 <!--     <a class="bottomLeftLogo" href="http://www.cartong.org/">
        <img src="{% static "./assets/img/CartONG_logo.png" %}" alt="CartONG">
      </a>-->

  </div><!-- /container-fluid-->


  <script type="text/javascript">
//    L.Icon.Default.imagePath = "{% static "./assets/img" %}";
    window.appConfig = {
//      testDataPath : "{% static "assets/testData.json" %}",
      faritraGeoJsonPath : "{% static "assets/faritra.json" %}",
      locale:'fr-FR'
    };
  </script>

{% endblock content%}

{% block load_js %}
  <script type="text/javascript" src="{% static "./assets/app.js" %}"></script>
  <script type="text/javascript" src="{% static "./assets/underscore-min.js" %}"></script>
  <script type="text/javascript" src="{% static "./assets/moment.js" %}"></script>
  <script src="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>
  <script type="text/javascript" src="{% static "./assets/leaflet.markercluster.js" %}"></script>
{% endblock load_js %}